name: rekor-goreleaser

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: mbestavros/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      -
        name: Echo signatures
        run: cat ./dist/checksums.txt.sig
      -
        name: Setup rekor
        run: |
          git clone https://github.com/SigStore/rekor.git
          cd ./rekor/cmd/cli
          go build -o rekor
      -
        name: Run rekor
        run: ./rekor/cmd/cli/rekor upload --rekor_server https://api.rekor.dev --signature ./dist/checksums.txt.sig --public-key ./pubkey.key --artifact ./dist/hello-go_linux_amd64/hello-go
